### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by PouyaJalali** [INFO-511-F24/final-project-LeanMeanLearningMachines#2]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Derek Rice - @derekriceX
- Shreya Kolte - @shreyakolte
- Pouya Jalali Khalilabadi - @PouyaJalali

- Describe the goal of the project.

    * The goal is to explore flight patterns at Belgian airports, especially focusing on Brussels Airport, to see how it compares to other airports and how seasonal trends might influence flight traffic.

- Describe the data used or collected.

    * This data comes from Eurocontrol, an international organization for air traffic control management throughout Europe. Air Traffic Flow Management (ATFM) collects information on daily flights arriving and departing European airports. This data contains {python} len(flights_dt.columns) columns and {python} len(flights_dt) rows for flights from the years of 2017 to 2022.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

    * The research question will be answered through data preprocessing, exploratory data analysis, time-series visualizations, and statistical comparisons. Seasonal trends will be visualized using bar plots and line graphs. Hypothesis tests like Chi-Square or Kruskal-Wallis H-tests may be used to determine statistical significance.

- Is there anything that is unclear from the proposal?

    * Hypothesis Testing: Using Chi-Square Test or H - Test depending on the output.
    * Unclear: how to use hypothesis testing to answer questions? Anova testing and/or t-test?

- Provide constructive feedback on how the team might be able to improve their project.

    * Consider adding more detail about the preprocessing steps for handling missing data and converting date formats.
    * Consider adding models to predict future seasonal travel.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

    * The results of the hypothesis testing and predictive modeling

- Provide constructive feedback on any issues with file and/or code organization.

    * You can leverage ANOVA to look at a difference in means between categorical variables like Airport/Country flights per hour for example, Multi-variable regression analysis can be used to create a model of seasonal travel between airports and/or countries

- (Optional) Any further comments or feedback?

**Comment by MichellesCode** [comment]
Thank you for the feedback!
