### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by DMStea** [INFO-511-F24/final-project-LeanMeanLearningMachines#3]
Peer Review for  LeanMeanLearningMachines
Peer review by: Coding Wildcats
Names of team members that participated in this review:
Erika Kirkpatrick
Kai Shuen Neo
Danielle Stea
Sahand Motameni
Rohit Kalakala

Describe the goal of the project.
The goal of the project is to determine how the total number of monthly flights at Brussels Airport compare to other major airports in Belgium and what season trends can be established.

Describe the data used or collected, if any. If the proposal does not include the use of a specific dataset, comment on whether the project would be strengthened by the inclusion of a dataset.
Yes, this proposal did include a specific dataset, the dataset came from Eurocontrol and was found using TidyTuesday Github. The dataset is from data collected by Air Traffic Flow Management about the daily flights arriving and departing from European airports in the years 2017 to 2022. The data contains 14 columns including date of the flight, airport name, country of the airport, etc.

Describe the approaches, tools, and methods that will be used.
The approaches, tools and methods that will be used include cleaning the data, and converting the data to a proper format, calculating summary statistics, creating time series graphs and bar charts. Depending on the output the team plans to use either a chi-square test or h-test to complete the statistical analysis.

Provide constructive feedback on how the team might be able to improve their project. Make sure your feedback includes at least one comment on the statistical reasoning aspect of the project, but do feel free to comment on aspects beyond the reasoning as well.
 One aspect of the project that could be improved is expanding the scope of the data slightly to account for external variables. For example, this data was collected from 2017 to 2022, in which time air travel was significantly impacted by COVID-19. Unless the group plans to take this detail into account, it might be helpful to consider the proportion of air travel per month in Brussels versus Europe as a whole or Belgium specifically.   

What aspect of this project are you most interested in and would like to see highlighted in the presentation.
One aspect of this project that we would like to see highlighted in the presentation is how similar or different the Belgium cities are, maybe give a brief introduction of the cites (population, size, etc.) as most students in the class are likely not familiar with Belgium cities so giving that information may help to put the data in context.

Were you able to reproduce the project by clicking on Render Website once you cloned it? Were there any issues with reproducibility?
We were successfully able to render the website.

Provide constructive feedback on any issues with file and/or code organization.
The project proposal is well-organized, though a little sparse on details. It seems that the contract is not fully filled out though, which might make assigning roles difficult.

What have you learned from this team’s project that you are considering implementing in your own project?
One aspect of this project that we will consider implementing is using visualizations to draw comparisons between variables, as this group will be looking at seasonal trends in air travel. Another aspect of this project which would be beneficial for our own project is narrowing the focus on a single city and using that as the focal point of comparison.

**Comment by MichellesCode** [comment]
Thank you for the feedback!
